/* C code for program sncExample, generated by snc from ./../sncExample.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
# line 2 "./../sncExample.stt"
static	double interval;
# line 3 "./../sncExample.stt"
static	double statusFlag;
# line 4 "./../sncExample.stt"
static	string logMsg;
# line 5 "./../sncExample.stt"
static	double pvToSet;
# line 6 "./../sncExample.stt"
static	int pvToSwitch;
# line 7 "./../sncExample.stt"
static	double parameters[36];
# line 8 "./../sncExample.stt"
static	double process_parameters[96];
# line 9 "./../sncExample.stt"
static	int devNo;
# line 10 "./../sncExample.stt"
static	string pvName;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 9 "./../sncExample.stt"
	static int seqg_initvar_devNo = 0;
	memcpy(&devNo, &seqg_initvar_devNo, sizeof(seqg_initvar_devNo));
	}
}

/****** Code for state "standBy" in state set "ssOnOff" ******/

/* Event function for state "standBy" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_standBy(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 168 "./../sncExample.stt"
	if (statusFlag == 0 && seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 173 "./../sncExample.stt"
	if (statusFlag == 1 && (devNo == 1 || devNo == 2 || devNo == 3 || devNo == 4 || devNo == 5 || devNo == 6 || devNo == 7 || devNo == 8))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 177 "./../sncExample.stt"
	if (statusFlag == 10 && (devNo == 1 || devNo == 2 || devNo == 3 || devNo == 4 || devNo == 5 || devNo == 6 || devNo == 7 || devNo == 8))
	{
		*seqg_pnst = 21;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "standBy" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_standBy(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 169 "./../sncExample.stt"
			sprintf(logMsg, "StandBy...");
# line 170 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 174 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: OnInit\n");
		}
		return;
	case 2:
		{
# line 178 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: OffInit\n");
		}
		return;
	}
}

/****** Code for state "OnInit" in state set "ssOnOff" ******/

/* Event function for state "OnInit" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnInit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 182 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnInit" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnInit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 183 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: On Init...", devNo);
# line 184 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 186 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:fixFrequency_set", devNo);
# line 187 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 188 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(0), DEFAULT, DEFAULT_TIMEOUT);
# line 189 "./../sncExample.stt"
			pvToSet = parameters[0];
# line 190 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 191 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 193 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:workPeriod_set", devNo);
# line 194 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 195 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(1), DEFAULT, DEFAULT_TIMEOUT);
# line 196 "./../sncExample.stt"
			pvToSet = parameters[1];
# line 197 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 198 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 200 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:amp_set", devNo);
# line 201 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 202 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(2), DEFAULT, DEFAULT_TIMEOUT);
# line 203 "./../sncExample.stt"
			pvToSet = parameters[2];
# line 204 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 205 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 207 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:FF_Delay_set", devNo);
# line 208 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 209 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(3), DEFAULT, DEFAULT_TIMEOUT);
# line 210 "./../sncExample.stt"
			pvToSet = parameters[3];
# line 211 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 212 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 214 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:PreTrig_Delay_set", devNo);
# line 215 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 216 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(4), DEFAULT, DEFAULT_TIMEOUT);
# line 217 "./../sncExample.stt"
			pvToSet = parameters[4];
# line 218 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 219 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 221 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampCoefficient_set", devNo);
# line 222 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 223 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(5), DEFAULT, DEFAULT_TIMEOUT);
# line 224 "./../sncExample.stt"
			pvToSet = parameters[5];
# line 225 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 226 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 228 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampPSet_set", devNo);
# line 229 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 230 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(6), DEFAULT, DEFAULT_TIMEOUT);
# line 231 "./../sncExample.stt"
			pvToSet = parameters[6];
# line 232 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 233 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 235 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampISet_set", devNo);
# line 236 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 237 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(7), DEFAULT, DEFAULT_TIMEOUT);
# line 238 "./../sncExample.stt"
			pvToSet = parameters[7];
# line 239 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 240 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 242 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 243 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 244 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(8), DEFAULT, DEFAULT_TIMEOUT);
# line 245 "./../sncExample.stt"
			pvToSet = parameters[8];
# line 246 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 247 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 249 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:fixTuningAngle_set", devNo);
# line 250 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 251 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(9), DEFAULT, DEFAULT_TIMEOUT);
# line 252 "./../sncExample.stt"
			pvToSet = parameters[9];
# line 253 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 254 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 256 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tunePSet_set", devNo);
# line 257 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 258 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(10), DEFAULT, DEFAULT_TIMEOUT);
# line 259 "./../sncExample.stt"
			pvToSet = parameters[10];
# line 260 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 261 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 263 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet_set", devNo);
# line 264 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 265 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(11), DEFAULT, DEFAULT_TIMEOUT);
# line 266 "./../sncExample.stt"
			pvToSet = parameters[11];
# line 267 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 268 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 270 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet1_set", devNo);
# line 271 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 272 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(12), DEFAULT, DEFAULT_TIMEOUT);
# line 273 "./../sncExample.stt"
			pvToSet = parameters[12];
# line 274 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 275 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 277 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet2_set", devNo);
# line 278 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 279 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(13), DEFAULT, DEFAULT_TIMEOUT);
# line 280 "./../sncExample.stt"
			pvToSet = parameters[13];
# line 281 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 282 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 284 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet3_set", devNo);
# line 285 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 286 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(14), DEFAULT, DEFAULT_TIMEOUT);
# line 287 "./../sncExample.stt"
			pvToSet = parameters[14];
# line 288 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 289 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 291 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 292 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 293 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(15), DEFAULT, DEFAULT_TIMEOUT);
# line 294 "./../sncExample.stt"
			pvToSet = parameters[15];
# line 295 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 296 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 298 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontFixTuningAngle_set", devNo);
# line 299 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 300 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(16), DEFAULT, DEFAULT_TIMEOUT);
# line 301 "./../sncExample.stt"
			pvToSet = parameters[16];
# line 302 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 303 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 305 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTunePSet_set", devNo);
# line 306 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 307 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(17), DEFAULT, DEFAULT_TIMEOUT);
# line 308 "./../sncExample.stt"
			pvToSet = parameters[17];
# line 309 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 310 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 312 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneISet_set", devNo);
# line 313 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 314 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(18), DEFAULT, DEFAULT_TIMEOUT);
# line 315 "./../sncExample.stt"
			pvToSet = parameters[18];
# line 316 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 317 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 319 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:initial_Phase_set", devNo);
# line 320 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 321 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(19), DEFAULT, DEFAULT_TIMEOUT);
# line 322 "./../sncExample.stt"
			pvToSet = parameters[19];
# line 323 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 324 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 326 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phase_p_set", devNo);
# line 327 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 328 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(20), DEFAULT, DEFAULT_TIMEOUT);
# line 329 "./../sncExample.stt"
			pvToSet = parameters[20];
# line 330 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 331 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 333 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phase_i_set", devNo);
# line 334 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 335 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(21), DEFAULT, DEFAULT_TIMEOUT);
# line 336 "./../sncExample.stt"
			pvToSet = parameters[21];
# line 337 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 338 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 340 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:pointSweep_set", devNo);
# line 341 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 342 "./../sncExample.stt"
			pvToSwitch = 1;
# line 343 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 344 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 346 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:sweepOption_set", devNo);
# line 347 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 348 "./../sncExample.stt"
			pvToSwitch = 1;
# line 349 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 350 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 352 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:intEnable_set", devNo);
# line 353 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 354 "./../sncExample.stt"
			pvToSwitch = 1;
# line 355 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 356 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 358 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:sgMode_set", devNo);
# line 359 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 360 "./../sncExample.stt"
			pvToSwitch = 1;
# line 361 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 362 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 364 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampOption_set", devNo);
# line 365 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 366 "./../sncExample.stt"
			pvToSwitch = 0;
# line 367 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 368 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 370 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampFFOption_set", devNo);
# line 371 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 372 "./../sncExample.stt"
			pvToSwitch = 0;
# line 373 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 374 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 376 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampModifyOption_set", devNo);
# line 377 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 378 "./../sncExample.stt"
			pvToSwitch = 0;
# line 379 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 380 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 382 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneOption_set", devNo);
# line 383 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 384 "./../sncExample.stt"
			pvToSwitch = 0;
# line 385 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 386 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 388 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneFFOption_set", devNo);
# line 389 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 390 "./../sncExample.stt"
			pvToSwitch = 0;
# line 391 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 392 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 394 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneModifyOption_set", devNo);
# line 395 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 396 "./../sncExample.stt"
			pvToSwitch = 0;
# line 397 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 398 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 400 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneOption_set", devNo);
# line 401 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 402 "./../sncExample.stt"
			pvToSwitch = 0;
# line 403 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 404 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 406 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseOption_set", devNo);
# line 407 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 408 "./../sncExample.stt"
			pvToSwitch = 0;
# line 409 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 410 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 412 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseFFOption_set", devNo);
# line 413 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 414 "./../sncExample.stt"
			pvToSwitch = 0;
# line 415 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 416 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 418 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseModifyOption_set", devNo);
# line 419 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 420 "./../sncExample.stt"
			pvToSwitch = 0;
# line 421 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 422 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 424 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:rfReset_set", devNo);
# line 425 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 426 "./../sncExample.stt"
			pvToSwitch = 1;
# line 427 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 428 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 430 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:drvReset_set", devNo);
# line 431 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 432 "./../sncExample.stt"
			pvToSwitch = 1;
# line 433 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 434 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 436 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:rfReset_set", devNo);
# line 437 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 438 "./../sncExample.stt"
			pvToSwitch = 1;
# line 439 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 440 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 442 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:drvReset_set", devNo);
# line 443 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 444 "./../sncExample.stt"
			pvToSwitch = 1;
# line 445 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 446 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 448 "./../sncExample.stt"
			printf("AutoOnOff: On Init System: End\n");
		}
		return;
	}
}

/****** Code for state "OnInit2" in state set "ssOnOff" ******/

/* Event function for state "OnInit2" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnInit2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 452 "./../sncExample.stt"
	if (devNo == 1)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 454 "./../sncExample.stt"
	if (devNo == 2)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 468 "./../sncExample.stt"
	if (devNo == 3)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 482 "./../sncExample.stt"
	if (devNo == 4)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 496 "./../sncExample.stt"
	if (devNo == 5)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 510 "./../sncExample.stt"
	if (devNo == 6)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 524 "./../sncExample.stt"
	if (devNo == 7)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 6;
		return TRUE;
	}
# line 538 "./../sncExample.stt"
	if (devNo == 8)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 7;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnInit2" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnInit2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 455 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 456 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 457 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(22), DEFAULT, DEFAULT_TIMEOUT);
# line 458 "./../sncExample.stt"
			pvToSet = parameters[22];
# line 459 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 460 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 461 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 462 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 463 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(23), DEFAULT, DEFAULT_TIMEOUT);
# line 464 "./../sncExample.stt"
			pvToSet = parameters[23];
# line 465 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 466 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 2:
		{
# line 469 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 470 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 471 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(24), DEFAULT, DEFAULT_TIMEOUT);
# line 472 "./../sncExample.stt"
			pvToSet = parameters[24];
# line 473 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 474 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 475 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 476 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 477 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(25), DEFAULT, DEFAULT_TIMEOUT);
# line 478 "./../sncExample.stt"
			pvToSet = parameters[25];
# line 479 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 480 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 3:
		{
# line 483 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 484 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 485 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(26), DEFAULT, DEFAULT_TIMEOUT);
# line 486 "./../sncExample.stt"
			pvToSet = parameters[26];
# line 487 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 488 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 489 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 490 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 491 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(27), DEFAULT, DEFAULT_TIMEOUT);
# line 492 "./../sncExample.stt"
			pvToSet = parameters[27];
# line 493 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 494 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 4:
		{
# line 497 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 498 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 499 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(28), DEFAULT, DEFAULT_TIMEOUT);
# line 500 "./../sncExample.stt"
			pvToSet = parameters[28];
# line 501 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 502 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 503 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 504 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 505 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(29), DEFAULT, DEFAULT_TIMEOUT);
# line 506 "./../sncExample.stt"
			pvToSet = parameters[29];
# line 507 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 508 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 5:
		{
# line 511 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 512 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 513 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(30), DEFAULT, DEFAULT_TIMEOUT);
# line 514 "./../sncExample.stt"
			pvToSet = parameters[30];
# line 515 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 516 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 517 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 518 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 519 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(31), DEFAULT, DEFAULT_TIMEOUT);
# line 520 "./../sncExample.stt"
			pvToSet = parameters[31];
# line 521 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 522 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 6:
		{
# line 525 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 526 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 527 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(32), DEFAULT, DEFAULT_TIMEOUT);
# line 528 "./../sncExample.stt"
			pvToSet = parameters[32];
# line 529 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 530 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 531 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 532 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 533 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(33), DEFAULT, DEFAULT_TIMEOUT);
# line 534 "./../sncExample.stt"
			pvToSet = parameters[33];
# line 535 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 536 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	case 7:
		{
# line 539 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:biasSet_set", devNo);
# line 540 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 541 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(34), DEFAULT, DEFAULT_TIMEOUT);
# line 542 "./../sncExample.stt"
			pvToSet = parameters[34];
# line 543 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 544 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 545 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontBiasSet_set", devNo);
# line 546 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 547 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 0/*parameters*/ + (CH_ID)(35), DEFAULT, DEFAULT_TIMEOUT);
# line 548 "./../sncExample.stt"
			pvToSet = parameters[35];
# line 549 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 550 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
		}
		return;
	}
}

/****** Code for state "OnModify" in state set "ssOnOff" ******/

/* Event function for state "OnModify" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnModify(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 554 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnModify" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnModify(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 555 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Modify\n");
# line 556 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn On Modify...", devNo);
# line 557 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 559 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampModifyOption_set", devNo);
# line 560 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 561 "./../sncExample.stt"
			pvToSwitch = 1;
# line 562 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 563 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 565 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneModifyOption_set", devNo);
# line 566 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 567 "./../sncExample.stt"
			pvToSwitch = 1;
# line 568 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 569 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 571 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseModifyOption_set", devNo);
# line 572 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 573 "./../sncExample.stt"
			pvToSwitch = 1;
# line 574 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 575 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 577 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Modify End\n");
		}
		return;
	}
}

/****** Code for state "OnReset" in state set "ssOnOff" ******/

/* Event function for state "OnReset" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnReset(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 581 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnReset" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnReset(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 582 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Reset System\n");
# line 583 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Reset System...", devNo);
# line 584 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 586 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:rfReset_set", devNo);
# line 587 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 588 "./../sncExample.stt"
			pvToSwitch = 1;
# line 589 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 590 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 592 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:drvReset_set", devNo);
# line 593 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 594 "./../sncExample.stt"
			pvToSwitch = 1;
# line 595 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 596 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 598 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:rfReset_set", devNo);
# line 599 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 600 "./../sncExample.stt"
			pvToSwitch = 1;
# line 601 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 602 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 604 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:drvReset_set", devNo);
# line 605 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 606 "./../sncExample.stt"
			pvToSwitch = 1;
# line 607 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 608 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 610 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Reset System End\n");
		}
		return;
	}
}

/****** Code for state "OnAmpPoint" in state set "ssOnOff" ******/

/* Event function for state "OnAmpPoint" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnAmpPoint(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 614 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnAmpPoint" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnAmpPoint(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 615 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Set Amp Point Value\n");
# line 616 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Set Amp Point...", devNo);
# line 617 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 619 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:amp_set", devNo);
# line 620 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 621 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 0), DEFAULT, DEFAULT_TIMEOUT);
# line 622 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 0];
# line 623 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 624 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 626 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Set Amp Point Value End\n");
		}
		return;
	}
}

/****** Code for state "OnCloseTuneLoop" in state set "ssOnOff" ******/

/* Event function for state "OnCloseTuneLoop" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnCloseTuneLoop(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 630 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnCloseTuneLoop" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnCloseTuneLoop(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 631 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Tune Loop\n");
# line 632 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Close Tune Loop...", devNo);
# line 633 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 635 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneOption_set", devNo);
# line 636 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 637 "./../sncExample.stt"
			pvToSwitch = 1;
# line 638 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 639 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 641 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Tune Loop End\n");
		}
		return;
	}
}

/****** Code for state "OnCloseGridTune" in state set "ssOnOff" ******/

/* Event function for state "OnCloseGridTune" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnCloseGridTune(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 645 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnCloseGridTune" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnCloseGridTune(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 646 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Grid Tune\n");
# line 647 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Close Grid Tune...", devNo);
# line 648 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 650 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneOption_set", devNo);
# line 651 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 652 "./../sncExample.stt"
			pvToSwitch = 1;
# line 653 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 654 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 656 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Grid Tune End\n");
		}
		return;
	}
}

/****** Code for state "OnTuneFF" in state set "ssOnOff" ******/

/* Event function for state "OnTuneFF" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnTuneFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 660 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnTuneFF" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnTuneFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 661 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Tune FF\n");
# line 662 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn On Tune FF...", devNo);
# line 663 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 665 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneFFOption_set", devNo);
# line 666 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 667 "./../sncExample.stt"
			pvToSwitch = 1;
# line 668 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 669 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 671 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Tune FF End\n");
		}
		return;
	}
}

/****** Code for state "OnTuneMOff" in state set "ssOnOff" ******/

/* Event function for state "OnTuneMOff" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnTuneMOff(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 675 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval * 1.6))
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnTuneMOff" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnTuneMOff(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 676 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn Off Tune M\n");
# line 677 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn Off Tune M...", devNo);
# line 678 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 680 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneModifyOption_set", devNo);
# line 681 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 682 "./../sncExample.stt"
			pvToSwitch = 0;
# line 683 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 684 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 686 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn Off Tune M End\n");
		}
		return;
	}
}

/****** Code for state "OnGridTuneISet" in state set "ssOnOff" ******/

/* Event function for state "OnGridTuneISet" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnGridTuneISet(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 690 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnGridTuneISet" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnGridTuneISet(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 691 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune Grid I Set\n");
# line 692 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Grid Tune I Set...", devNo);
# line 693 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 695 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneISet_set", devNo);
# line 696 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 697 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 1), DEFAULT, DEFAULT_TIMEOUT);
# line 698 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 1];
# line 699 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 700 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 702 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune I Set End\n");
		}
		return;
	}
}

/****** Code for state "OnCloseAmpLoop" in state set "ssOnOff" ******/

/* Event function for state "OnCloseAmpLoop" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnCloseAmpLoop(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 706 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnCloseAmpLoop" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnCloseAmpLoop(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 707 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Amp Loop\n");
# line 708 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Close Amp Loop...", devNo);
# line 709 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 711 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampOption_set", devNo);
# line 712 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 713 "./../sncExample.stt"
			pvToSwitch = 1;
# line 714 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 715 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 717 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Amp Loop End\n");
		}
		return;
	}
}

/****** Code for state "OnTuneISet" in state set "ssOnOff" ******/

/* Event function for state "OnTuneISet" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnTuneISet(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 721 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnTuneISet" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnTuneISet(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 722 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune I Set\n");
# line 723 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Tune I Set...", devNo);
# line 724 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 726 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet_set", devNo);
# line 727 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 728 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 2), DEFAULT, DEFAULT_TIMEOUT);
# line 729 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 2];
# line 730 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 731 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 733 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet1_set", devNo);
# line 734 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 735 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 3), DEFAULT, DEFAULT_TIMEOUT);
# line 736 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 3];
# line 737 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 738 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 740 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet2_set", devNo);
# line 741 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 742 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 4), DEFAULT, DEFAULT_TIMEOUT);
# line 743 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 4];
# line 744 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 745 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 747 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet3_set", devNo);
# line 748 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 749 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 5), DEFAULT, DEFAULT_TIMEOUT);
# line 750 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 5];
# line 751 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 752 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 754 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune I Set End\n");
		}
		return;
	}
}

/****** Code for state "OnAmpFF" in state set "ssOnOff" ******/

/* Event function for state "OnAmpFF" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnAmpFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 758 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnAmpFF" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnAmpFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 759 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Amp FF\n");
# line 760 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn On Amp FF...", devNo);
# line 761 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 763 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampFFOption_set", devNo);
# line 764 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 765 "./../sncExample.stt"
			pvToSwitch = 1;
# line 766 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 767 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 769 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Amp FF End\n");
		}
		return;
	}
}

/****** Code for state "OnAmpCoefficUp1" in state set "ssOnOff" ******/

/* Event function for state "OnAmpCoefficUp1" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnAmpCoefficUp1(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 773 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnAmpCoefficUp1" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnAmpCoefficUp1(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 774 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up\n");
# line 775 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Amp Coeffic Up...", devNo);
# line 776 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 778 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampCoefficient_set", devNo);
# line 779 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 780 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 6), DEFAULT, DEFAULT_TIMEOUT);
# line 781 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 6];
# line 782 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 783 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 785 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up 1 End\n");
		}
		return;
	}
}

/****** Code for state "OnAmpCoefficUp2" in state set "ssOnOff" ******/

/* Event function for state "OnAmpCoefficUp2" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnAmpCoefficUp2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 789 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnAmpCoefficUp2" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnAmpCoefficUp2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 790 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up\n");
# line 791 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Amp Coeffic Up...", devNo);
# line 792 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 794 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampCoefficient_set", devNo);
# line 795 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 796 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 7), DEFAULT, DEFAULT_TIMEOUT);
# line 797 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 7];
# line 798 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 799 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 801 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up 2 End\n");
		}
		return;
	}
}

/****** Code for state "OnAmpCoefficUp3" in state set "ssOnOff" ******/

/* Event function for state "OnAmpCoefficUp3" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnAmpCoefficUp3(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 805 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnAmpCoefficUp3" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnAmpCoefficUp3(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 806 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up\n");
# line 807 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Amp Coeffic Up...", devNo);
# line 808 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 810 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:ampCoefficient_set", devNo);
# line 811 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 812 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 8), DEFAULT, DEFAULT_TIMEOUT);
# line 813 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 8];
# line 814 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 815 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 817 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Amp Coeffic Up 3 End\n");
		}
		return;
	}
}

/****** Code for state "OnTuneComplexI" in state set "ssOnOff" ******/

/* Event function for state "OnTuneComplexI" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnTuneComplexI(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 821 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnTuneComplexI" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnTuneComplexI(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 822 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune Complex I\n");
# line 823 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Tune Complex I...", devNo);
# line 824 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 826 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneISet_set", devNo);
# line 827 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 828 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 9), DEFAULT, DEFAULT_TIMEOUT);
# line 829 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 9];
# line 830 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 831 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 833 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneISet3_set", devNo);
# line 834 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 835 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 10), DEFAULT, DEFAULT_TIMEOUT);
# line 836 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 10];
# line 837 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 838 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 840 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune Complex I End\n");
		}
		return;
	}
}

/****** Code for state "OnTuneFFAgain" in state set "ssOnOff" ******/

/* Event function for state "OnTuneFFAgain" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnTuneFFAgain(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 844 "./../sncExample.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnTuneFFAgain" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnTuneFFAgain(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 845 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune FF Again\n");
# line 846 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Tune FF Again...", devNo);
# line 847 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 849 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:tuneModifyOption_set", devNo);
# line 850 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 851 "./../sncExample.stt"
			pvToSwitch = 1;
# line 852 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 853 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 855 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Tune FF Again End\n");
		}
		return;
	}
}

/****** Code for state "OnClosePhaseLoop" in state set "ssOnOff" ******/

/* Event function for state "OnClosePhaseLoop" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnClosePhaseLoop(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 859 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 20;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnClosePhaseLoop" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnClosePhaseLoop(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 860 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Phase Loop\n");
# line 861 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Close Phase Loop...", devNo);
# line 862 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 864 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseOption_set", devNo);
# line 865 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 866 "./../sncExample.stt"
			pvToSwitch = 1;
# line 867 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 868 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 870 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Close Phase Loop End\n");
		}
		return;
	}
}

/****** Code for state "OnPhaseFF" in state set "ssOnOff" ******/

/* Event function for state "OnPhaseFF" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OnPhaseFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 874 "./../sncExample.stt"
	if (seq_delay(seqg_env, interval))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OnPhaseFF" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OnPhaseFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 875 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Phase FF\n");
# line 876 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn On Phase FF...", devNo);
# line 877 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 879 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseFFOption_set", devNo);
# line 880 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 881 "./../sncExample.stt"
			pvToSwitch = 1;
# line 882 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 883 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 885 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On Phase FF End\n");
# line 886 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn On System End", devNo);
# line 887 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 888 "./../sncExample.stt"
			printf("AutoOnOff: Turn On System: Turn On System End\n");
# line 889 "./../sncExample.stt"
			statusFlag = 0;
# line 890 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 133/*statusFlag*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "OffInit" in state set "ssOnOff" ******/

/* Event function for state "OffInit" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OffInit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 894 "./../sncExample.stt"
	if (seq_delay(seqg_env, 0.5))
	{
		*seqg_pnst = 22;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OffInit" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OffInit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 895 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Off Init", devNo);
# line 896 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 898 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Open Phase Loop...\n");
# line 900 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:phaseOption_set", devNo);
# line 901 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 902 "./../sncExample.stt"
			pvToSwitch = 0;
# line 903 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 904 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 906 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Open Phase Loop End\n");
		}
		return;
	}
}

/****** Code for state "OffOpenGridLoop" in state set "ssOnOff" ******/

/* Event function for state "OffOpenGridLoop" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OffOpenGridLoop(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 910 "./../sncExample.stt"
	if (seq_delay(seqg_env, 0.5))
	{
		*seqg_pnst = 23;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OffOpenGridLoop" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OffOpenGridLoop(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 911 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Open Grid Tune Loop", devNo);
# line 912 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 914 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Open Grid Loop\n");
# line 916 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:frontTuneOption_set", devNo);
# line 917 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 137/*pvToSwitch*/, pvName);
# line 918 "./../sncExample.stt"
			pvToSwitch = 0;
# line 919 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 137/*pvToSwitch*/, DEFAULT, DEFAULT_TIMEOUT);
# line 920 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %d\n", pvName, pvToSwitch);
# line 922 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Open Grid Tune Loop End\n");
		}
		return;
	}
}

/****** Code for state "OffAmpZero" in state set "ssOnOff" ******/

/* Event function for state "OffAmpZero" in state set "ssOnOff" */
static seqBool seqg_event_ssOnOff_0_OffAmpZero(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 926 "./../sncExample.stt"
	if (seq_delay(seqg_env, 0.5))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "OffAmpZero" in state set "ssOnOff" */
static void seqg_action_ssOnOff_0_OffAmpZero(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 927 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Amp Zero", devNo);
# line 928 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 929 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Amp Zero\n");
# line 931 "./../sncExample.stt"
			sprintf(pvName, "AutoOnOff:rcsRf%d:amp_set", devNo);
# line 932 "./../sncExample.stt"
			seq_pvAssign(seqg_env, 136/*pvToSet*/, pvName);
# line 933 "./../sncExample.stt"
			seq_pvGetTmo(seqg_env, 36/*process_parameters*/ + (CH_ID)(12 * (devNo - 1) + 11), DEFAULT, DEFAULT_TIMEOUT);
# line 934 "./../sncExample.stt"
			pvToSet = process_parameters[12 * (devNo - 1) + 11];
# line 935 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 136/*pvToSet*/, DEFAULT, DEFAULT_TIMEOUT);
# line 936 "./../sncExample.stt"
			printf("AutoOnOff: %s is set to: %f\n", pvName, pvToSet);
# line 938 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Amp Zero End\n");
# line 939 "./../sncExample.stt"
			printf("AutoOnOff: Turn Off System: Turn Off System End\n");
# line 940 "./../sncExample.stt"
			sprintf(logMsg, "AutoOnOff:rcsRf%d: Turn Off System End", devNo);
# line 941 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 132/*logMsg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 942 "./../sncExample.stt"
			statusFlag = 0;
# line 943 "./../sncExample.stt"
			seq_pvPutTmo(seqg_env, 133/*statusFlag*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"AutoOnOff:Parameter0", (size_t)&parameters[0], "parameters[0]", P_DOUBLE, 1, 1, 0, 0, 0, 0},
	{"AutoOnOff:Parameter1", (size_t)&parameters[1], "parameters[1]", P_DOUBLE, 1, 2, 0, 0, 0, 0},
	{"AutoOnOff:Parameter2", (size_t)&parameters[2], "parameters[2]", P_DOUBLE, 1, 3, 0, 0, 0, 0},
	{"AutoOnOff:Parameter3", (size_t)&parameters[3], "parameters[3]", P_DOUBLE, 1, 4, 0, 0, 0, 0},
	{"AutoOnOff:Parameter4", (size_t)&parameters[4], "parameters[4]", P_DOUBLE, 1, 5, 0, 0, 0, 0},
	{"AutoOnOff:Parameter5", (size_t)&parameters[5], "parameters[5]", P_DOUBLE, 1, 6, 0, 0, 0, 0},
	{"AutoOnOff:Parameter6", (size_t)&parameters[6], "parameters[6]", P_DOUBLE, 1, 7, 0, 0, 0, 0},
	{"AutoOnOff:Parameter7", (size_t)&parameters[7], "parameters[7]", P_DOUBLE, 1, 8, 0, 0, 0, 0},
	{"AutoOnOff:Parameter8", (size_t)&parameters[8], "parameters[8]", P_DOUBLE, 1, 9, 0, 0, 0, 0},
	{"AutoOnOff:Parameter9", (size_t)&parameters[9], "parameters[9]", P_DOUBLE, 1, 10, 0, 0, 0, 0},
	{"AutoOnOff:Parameter10", (size_t)&parameters[10], "parameters[10]", P_DOUBLE, 1, 11, 0, 0, 0, 0},
	{"AutoOnOff:Parameter11", (size_t)&parameters[11], "parameters[11]", P_DOUBLE, 1, 12, 0, 0, 0, 0},
	{"AutoOnOff:Parameter12", (size_t)&parameters[12], "parameters[12]", P_DOUBLE, 1, 13, 0, 0, 0, 0},
	{"AutoOnOff:Parameter13", (size_t)&parameters[13], "parameters[13]", P_DOUBLE, 1, 14, 0, 0, 0, 0},
	{"AutoOnOff:Parameter14", (size_t)&parameters[14], "parameters[14]", P_DOUBLE, 1, 15, 0, 0, 0, 0},
	{"AutoOnOff:Parameter15", (size_t)&parameters[15], "parameters[15]", P_DOUBLE, 1, 16, 0, 0, 0, 0},
	{"AutoOnOff:Parameter16", (size_t)&parameters[16], "parameters[16]", P_DOUBLE, 1, 17, 0, 0, 0, 0},
	{"AutoOnOff:Parameter17", (size_t)&parameters[17], "parameters[17]", P_DOUBLE, 1, 18, 0, 0, 0, 0},
	{"AutoOnOff:Parameter18", (size_t)&parameters[18], "parameters[18]", P_DOUBLE, 1, 19, 0, 0, 0, 0},
	{"AutoOnOff:Parameter19", (size_t)&parameters[19], "parameters[19]", P_DOUBLE, 1, 20, 0, 0, 0, 0},
	{"AutoOnOff:Parameter20", (size_t)&parameters[20], "parameters[20]", P_DOUBLE, 1, 21, 0, 0, 0, 0},
	{"AutoOnOff:Parameter21", (size_t)&parameters[21], "parameters[21]", P_DOUBLE, 1, 22, 0, 0, 0, 0},
	{"AutoOnOff:Parameter22", (size_t)&parameters[22], "parameters[22]", P_DOUBLE, 1, 23, 0, 0, 0, 0},
	{"AutoOnOff:Parameter23", (size_t)&parameters[23], "parameters[23]", P_DOUBLE, 1, 24, 0, 0, 0, 0},
	{"AutoOnOff:Parameter24", (size_t)&parameters[24], "parameters[24]", P_DOUBLE, 1, 25, 0, 0, 0, 0},
	{"AutoOnOff:Parameter25", (size_t)&parameters[25], "parameters[25]", P_DOUBLE, 1, 26, 0, 0, 0, 0},
	{"AutoOnOff:Parameter26", (size_t)&parameters[26], "parameters[26]", P_DOUBLE, 1, 27, 0, 0, 0, 0},
	{"AutoOnOff:Parameter27", (size_t)&parameters[27], "parameters[27]", P_DOUBLE, 1, 28, 0, 0, 0, 0},
	{"AutoOnOff:Parameter28", (size_t)&parameters[28], "parameters[28]", P_DOUBLE, 1, 29, 0, 0, 0, 0},
	{"AutoOnOff:Parameter29", (size_t)&parameters[29], "parameters[29]", P_DOUBLE, 1, 30, 0, 0, 0, 0},
	{"AutoOnOff:Parameter30", (size_t)&parameters[30], "parameters[30]", P_DOUBLE, 1, 31, 0, 0, 0, 0},
	{"AutoOnOff:Parameter31", (size_t)&parameters[31], "parameters[31]", P_DOUBLE, 1, 32, 0, 0, 0, 0},
	{"AutoOnOff:Parameter32", (size_t)&parameters[32], "parameters[32]", P_DOUBLE, 1, 33, 0, 0, 0, 0},
	{"AutoOnOff:Parameter33", (size_t)&parameters[33], "parameters[33]", P_DOUBLE, 1, 34, 0, 0, 0, 0},
	{"AutoOnOff:Parameter34", (size_t)&parameters[34], "parameters[34]", P_DOUBLE, 1, 35, 0, 0, 0, 0},
	{"AutoOnOff:Parameter35", (size_t)&parameters[35], "parameters[35]", P_DOUBLE, 1, 36, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter0", (size_t)&process_parameters[0], "process_parameters[0]", P_DOUBLE, 1, 37, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter1", (size_t)&process_parameters[1], "process_parameters[1]", P_DOUBLE, 1, 38, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter2", (size_t)&process_parameters[2], "process_parameters[2]", P_DOUBLE, 1, 39, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter3", (size_t)&process_parameters[3], "process_parameters[3]", P_DOUBLE, 1, 40, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter4", (size_t)&process_parameters[4], "process_parameters[4]", P_DOUBLE, 1, 41, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter5", (size_t)&process_parameters[5], "process_parameters[5]", P_DOUBLE, 1, 42, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter6", (size_t)&process_parameters[6], "process_parameters[6]", P_DOUBLE, 1, 43, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter7", (size_t)&process_parameters[7], "process_parameters[7]", P_DOUBLE, 1, 44, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter8", (size_t)&process_parameters[8], "process_parameters[8]", P_DOUBLE, 1, 45, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter9", (size_t)&process_parameters[9], "process_parameters[9]", P_DOUBLE, 1, 46, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter10", (size_t)&process_parameters[10], "process_parameters[10]", P_DOUBLE, 1, 47, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter11", (size_t)&process_parameters[11], "process_parameters[11]", P_DOUBLE, 1, 48, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter12", (size_t)&process_parameters[12], "process_parameters[12]", P_DOUBLE, 1, 49, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter13", (size_t)&process_parameters[13], "process_parameters[13]", P_DOUBLE, 1, 50, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter14", (size_t)&process_parameters[14], "process_parameters[14]", P_DOUBLE, 1, 51, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter15", (size_t)&process_parameters[15], "process_parameters[15]", P_DOUBLE, 1, 52, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter16", (size_t)&process_parameters[16], "process_parameters[16]", P_DOUBLE, 1, 53, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter17", (size_t)&process_parameters[17], "process_parameters[17]", P_DOUBLE, 1, 54, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter18", (size_t)&process_parameters[18], "process_parameters[18]", P_DOUBLE, 1, 55, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter19", (size_t)&process_parameters[19], "process_parameters[19]", P_DOUBLE, 1, 56, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter20", (size_t)&process_parameters[20], "process_parameters[20]", P_DOUBLE, 1, 57, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter21", (size_t)&process_parameters[21], "process_parameters[21]", P_DOUBLE, 1, 58, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter22", (size_t)&process_parameters[22], "process_parameters[22]", P_DOUBLE, 1, 59, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter23", (size_t)&process_parameters[23], "process_parameters[23]", P_DOUBLE, 1, 60, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter24", (size_t)&process_parameters[24], "process_parameters[24]", P_DOUBLE, 1, 61, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter25", (size_t)&process_parameters[25], "process_parameters[25]", P_DOUBLE, 1, 62, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter26", (size_t)&process_parameters[26], "process_parameters[26]", P_DOUBLE, 1, 63, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter27", (size_t)&process_parameters[27], "process_parameters[27]", P_DOUBLE, 1, 64, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter28", (size_t)&process_parameters[28], "process_parameters[28]", P_DOUBLE, 1, 65, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter29", (size_t)&process_parameters[29], "process_parameters[29]", P_DOUBLE, 1, 66, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter30", (size_t)&process_parameters[30], "process_parameters[30]", P_DOUBLE, 1, 67, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter31", (size_t)&process_parameters[31], "process_parameters[31]", P_DOUBLE, 1, 68, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter32", (size_t)&process_parameters[32], "process_parameters[32]", P_DOUBLE, 1, 69, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter33", (size_t)&process_parameters[33], "process_parameters[33]", P_DOUBLE, 1, 70, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter34", (size_t)&process_parameters[34], "process_parameters[34]", P_DOUBLE, 1, 71, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter35", (size_t)&process_parameters[35], "process_parameters[35]", P_DOUBLE, 1, 72, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter36", (size_t)&process_parameters[36], "process_parameters[36]", P_DOUBLE, 1, 73, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter37", (size_t)&process_parameters[37], "process_parameters[37]", P_DOUBLE, 1, 74, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter38", (size_t)&process_parameters[38], "process_parameters[38]", P_DOUBLE, 1, 75, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter39", (size_t)&process_parameters[39], "process_parameters[39]", P_DOUBLE, 1, 76, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter40", (size_t)&process_parameters[40], "process_parameters[40]", P_DOUBLE, 1, 77, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter41", (size_t)&process_parameters[41], "process_parameters[41]", P_DOUBLE, 1, 78, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter42", (size_t)&process_parameters[42], "process_parameters[42]", P_DOUBLE, 1, 79, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter43", (size_t)&process_parameters[43], "process_parameters[43]", P_DOUBLE, 1, 80, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter44", (size_t)&process_parameters[44], "process_parameters[44]", P_DOUBLE, 1, 81, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter45", (size_t)&process_parameters[45], "process_parameters[45]", P_DOUBLE, 1, 82, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter46", (size_t)&process_parameters[46], "process_parameters[46]", P_DOUBLE, 1, 83, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter47", (size_t)&process_parameters[47], "process_parameters[47]", P_DOUBLE, 1, 84, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter48", (size_t)&process_parameters[48], "process_parameters[48]", P_DOUBLE, 1, 85, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter49", (size_t)&process_parameters[49], "process_parameters[49]", P_DOUBLE, 1, 86, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter50", (size_t)&process_parameters[50], "process_parameters[50]", P_DOUBLE, 1, 87, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter51", (size_t)&process_parameters[51], "process_parameters[51]", P_DOUBLE, 1, 88, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter52", (size_t)&process_parameters[52], "process_parameters[52]", P_DOUBLE, 1, 89, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter53", (size_t)&process_parameters[53], "process_parameters[53]", P_DOUBLE, 1, 90, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter54", (size_t)&process_parameters[54], "process_parameters[54]", P_DOUBLE, 1, 91, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter55", (size_t)&process_parameters[55], "process_parameters[55]", P_DOUBLE, 1, 92, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter56", (size_t)&process_parameters[56], "process_parameters[56]", P_DOUBLE, 1, 93, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter57", (size_t)&process_parameters[57], "process_parameters[57]", P_DOUBLE, 1, 94, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter58", (size_t)&process_parameters[58], "process_parameters[58]", P_DOUBLE, 1, 95, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter59", (size_t)&process_parameters[59], "process_parameters[59]", P_DOUBLE, 1, 96, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter60", (size_t)&process_parameters[60], "process_parameters[60]", P_DOUBLE, 1, 97, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter61", (size_t)&process_parameters[61], "process_parameters[61]", P_DOUBLE, 1, 98, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter62", (size_t)&process_parameters[62], "process_parameters[62]", P_DOUBLE, 1, 99, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter63", (size_t)&process_parameters[63], "process_parameters[63]", P_DOUBLE, 1, 100, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter64", (size_t)&process_parameters[64], "process_parameters[64]", P_DOUBLE, 1, 101, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter65", (size_t)&process_parameters[65], "process_parameters[65]", P_DOUBLE, 1, 102, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter66", (size_t)&process_parameters[66], "process_parameters[66]", P_DOUBLE, 1, 103, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter67", (size_t)&process_parameters[67], "process_parameters[67]", P_DOUBLE, 1, 104, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter68", (size_t)&process_parameters[68], "process_parameters[68]", P_DOUBLE, 1, 105, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter69", (size_t)&process_parameters[69], "process_parameters[69]", P_DOUBLE, 1, 106, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter70", (size_t)&process_parameters[70], "process_parameters[70]", P_DOUBLE, 1, 107, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter71", (size_t)&process_parameters[71], "process_parameters[71]", P_DOUBLE, 1, 108, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter72", (size_t)&process_parameters[72], "process_parameters[72]", P_DOUBLE, 1, 109, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter73", (size_t)&process_parameters[73], "process_parameters[73]", P_DOUBLE, 1, 110, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter74", (size_t)&process_parameters[74], "process_parameters[74]", P_DOUBLE, 1, 111, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter75", (size_t)&process_parameters[75], "process_parameters[75]", P_DOUBLE, 1, 112, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter76", (size_t)&process_parameters[76], "process_parameters[76]", P_DOUBLE, 1, 113, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter77", (size_t)&process_parameters[77], "process_parameters[77]", P_DOUBLE, 1, 114, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter78", (size_t)&process_parameters[78], "process_parameters[78]", P_DOUBLE, 1, 115, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter79", (size_t)&process_parameters[79], "process_parameters[79]", P_DOUBLE, 1, 116, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter80", (size_t)&process_parameters[80], "process_parameters[80]", P_DOUBLE, 1, 117, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter81", (size_t)&process_parameters[81], "process_parameters[81]", P_DOUBLE, 1, 118, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter82", (size_t)&process_parameters[82], "process_parameters[82]", P_DOUBLE, 1, 119, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter83", (size_t)&process_parameters[83], "process_parameters[83]", P_DOUBLE, 1, 120, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter84", (size_t)&process_parameters[84], "process_parameters[84]", P_DOUBLE, 1, 121, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter85", (size_t)&process_parameters[85], "process_parameters[85]", P_DOUBLE, 1, 122, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter86", (size_t)&process_parameters[86], "process_parameters[86]", P_DOUBLE, 1, 123, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter87", (size_t)&process_parameters[87], "process_parameters[87]", P_DOUBLE, 1, 124, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter88", (size_t)&process_parameters[88], "process_parameters[88]", P_DOUBLE, 1, 125, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter89", (size_t)&process_parameters[89], "process_parameters[89]", P_DOUBLE, 1, 126, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter90", (size_t)&process_parameters[90], "process_parameters[90]", P_DOUBLE, 1, 127, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter91", (size_t)&process_parameters[91], "process_parameters[91]", P_DOUBLE, 1, 128, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter92", (size_t)&process_parameters[92], "process_parameters[92]", P_DOUBLE, 1, 129, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter93", (size_t)&process_parameters[93], "process_parameters[93]", P_DOUBLE, 1, 130, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter94", (size_t)&process_parameters[94], "process_parameters[94]", P_DOUBLE, 1, 131, 0, 0, 0, 0},
	{"AutoOnOff:Process_Parameter95", (size_t)&process_parameters[95], "process_parameters[95]", P_DOUBLE, 1, 132, 0, 0, 0, 0},
	{"AutoOnOff:logMsg", (size_t)&logMsg, "logMsg", P_STRING, 1, 133, 0, 0, 0, 0},
	{"AutoOnOff:StatusFlag", (size_t)&statusFlag, "statusFlag", P_DOUBLE, 1, 134, 0, 1, 0, 0},
	{"AutoOnOff:Interval", (size_t)&interval, "interval", P_DOUBLE, 1, 135, 0, 1, 0, 0},
	{"AutoOnOff:CavityNum", (size_t)&devNo, "devNo", P_INT, 1, 136, 0, 1, 0, 0},
	{"", (size_t)&pvToSet, "pvToSet", P_DOUBLE, 1, 137, 0, 0, 0, 0},
	{"", (size_t)&pvToSwitch, "pvToSwitch", P_INT, 1, 138, 0, 0, 0, 0},
};

/* Event masks for state set "ssOnOff" */
static const seqMask seqg_mask_ssOnOff_0_standBy[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000140,
};
static const seqMask seqg_mask_ssOnOff_0_OnInit[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnInit2[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000100,
};
static const seqMask seqg_mask_ssOnOff_0_OnModify[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnReset[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnAmpPoint[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnCloseTuneLoop[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnCloseGridTune[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnTuneFF[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnTuneMOff[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnGridTuneISet[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnCloseAmpLoop[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnTuneISet[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnAmpFF[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnAmpCoefficUp1[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnAmpCoefficUp2[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnAmpCoefficUp3[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnTuneComplexI[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnTuneFFAgain[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OnClosePhaseLoop[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OnPhaseFF[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000080,
};
static const seqMask seqg_mask_ssOnOff_0_OffInit[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OffOpenGridLoop[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ssOnOff_0_OffAmpZero[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "ssOnOff" */
static seqState seqg_states_ssOnOff[] = {
	{
	/* state name */        "standBy",
	/* action function */   seqg_action_ssOnOff_0_standBy,
	/* event function */    seqg_event_ssOnOff_0_standBy,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_standBy,
	/* state options */     (0)
	},
	{
	/* state name */        "OnInit",
	/* action function */   seqg_action_ssOnOff_0_OnInit,
	/* event function */    seqg_event_ssOnOff_0_OnInit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnInit,
	/* state options */     (0)
	},
	{
	/* state name */        "OnInit2",
	/* action function */   seqg_action_ssOnOff_0_OnInit2,
	/* event function */    seqg_event_ssOnOff_0_OnInit2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnInit2,
	/* state options */     (0)
	},
	{
	/* state name */        "OnModify",
	/* action function */   seqg_action_ssOnOff_0_OnModify,
	/* event function */    seqg_event_ssOnOff_0_OnModify,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnModify,
	/* state options */     (0)
	},
	{
	/* state name */        "OnReset",
	/* action function */   seqg_action_ssOnOff_0_OnReset,
	/* event function */    seqg_event_ssOnOff_0_OnReset,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnReset,
	/* state options */     (0)
	},
	{
	/* state name */        "OnAmpPoint",
	/* action function */   seqg_action_ssOnOff_0_OnAmpPoint,
	/* event function */    seqg_event_ssOnOff_0_OnAmpPoint,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnAmpPoint,
	/* state options */     (0)
	},
	{
	/* state name */        "OnCloseTuneLoop",
	/* action function */   seqg_action_ssOnOff_0_OnCloseTuneLoop,
	/* event function */    seqg_event_ssOnOff_0_OnCloseTuneLoop,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnCloseTuneLoop,
	/* state options */     (0)
	},
	{
	/* state name */        "OnCloseGridTune",
	/* action function */   seqg_action_ssOnOff_0_OnCloseGridTune,
	/* event function */    seqg_event_ssOnOff_0_OnCloseGridTune,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnCloseGridTune,
	/* state options */     (0)
	},
	{
	/* state name */        "OnTuneFF",
	/* action function */   seqg_action_ssOnOff_0_OnTuneFF,
	/* event function */    seqg_event_ssOnOff_0_OnTuneFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnTuneFF,
	/* state options */     (0)
	},
	{
	/* state name */        "OnTuneMOff",
	/* action function */   seqg_action_ssOnOff_0_OnTuneMOff,
	/* event function */    seqg_event_ssOnOff_0_OnTuneMOff,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnTuneMOff,
	/* state options */     (0)
	},
	{
	/* state name */        "OnGridTuneISet",
	/* action function */   seqg_action_ssOnOff_0_OnGridTuneISet,
	/* event function */    seqg_event_ssOnOff_0_OnGridTuneISet,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnGridTuneISet,
	/* state options */     (0)
	},
	{
	/* state name */        "OnCloseAmpLoop",
	/* action function */   seqg_action_ssOnOff_0_OnCloseAmpLoop,
	/* event function */    seqg_event_ssOnOff_0_OnCloseAmpLoop,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnCloseAmpLoop,
	/* state options */     (0)
	},
	{
	/* state name */        "OnTuneISet",
	/* action function */   seqg_action_ssOnOff_0_OnTuneISet,
	/* event function */    seqg_event_ssOnOff_0_OnTuneISet,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnTuneISet,
	/* state options */     (0)
	},
	{
	/* state name */        "OnAmpFF",
	/* action function */   seqg_action_ssOnOff_0_OnAmpFF,
	/* event function */    seqg_event_ssOnOff_0_OnAmpFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnAmpFF,
	/* state options */     (0)
	},
	{
	/* state name */        "OnAmpCoefficUp1",
	/* action function */   seqg_action_ssOnOff_0_OnAmpCoefficUp1,
	/* event function */    seqg_event_ssOnOff_0_OnAmpCoefficUp1,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnAmpCoefficUp1,
	/* state options */     (0)
	},
	{
	/* state name */        "OnAmpCoefficUp2",
	/* action function */   seqg_action_ssOnOff_0_OnAmpCoefficUp2,
	/* event function */    seqg_event_ssOnOff_0_OnAmpCoefficUp2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnAmpCoefficUp2,
	/* state options */     (0)
	},
	{
	/* state name */        "OnAmpCoefficUp3",
	/* action function */   seqg_action_ssOnOff_0_OnAmpCoefficUp3,
	/* event function */    seqg_event_ssOnOff_0_OnAmpCoefficUp3,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnAmpCoefficUp3,
	/* state options */     (0)
	},
	{
	/* state name */        "OnTuneComplexI",
	/* action function */   seqg_action_ssOnOff_0_OnTuneComplexI,
	/* event function */    seqg_event_ssOnOff_0_OnTuneComplexI,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnTuneComplexI,
	/* state options */     (0)
	},
	{
	/* state name */        "OnTuneFFAgain",
	/* action function */   seqg_action_ssOnOff_0_OnTuneFFAgain,
	/* event function */    seqg_event_ssOnOff_0_OnTuneFFAgain,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnTuneFFAgain,
	/* state options */     (0)
	},
	{
	/* state name */        "OnClosePhaseLoop",
	/* action function */   seqg_action_ssOnOff_0_OnClosePhaseLoop,
	/* event function */    seqg_event_ssOnOff_0_OnClosePhaseLoop,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnClosePhaseLoop,
	/* state options */     (0)
	},
	{
	/* state name */        "OnPhaseFF",
	/* action function */   seqg_action_ssOnOff_0_OnPhaseFF,
	/* event function */    seqg_event_ssOnOff_0_OnPhaseFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OnPhaseFF,
	/* state options */     (0)
	},
	{
	/* state name */        "OffInit",
	/* action function */   seqg_action_ssOnOff_0_OffInit,
	/* event function */    seqg_event_ssOnOff_0_OffInit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OffInit,
	/* state options */     (0)
	},
	{
	/* state name */        "OffOpenGridLoop",
	/* action function */   seqg_action_ssOnOff_0_OffOpenGridLoop,
	/* event function */    seqg_event_ssOnOff_0_OffOpenGridLoop,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OffOpenGridLoop,
	/* state options */     (0)
	},
	{
	/* state name */        "OffAmpZero",
	/* action function */   seqg_action_ssOnOff_0_OffAmpZero,
	/* event function */    seqg_event_ssOnOff_0_OffAmpZero,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ssOnOff_0_OffAmpZero,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ssOnOff",
	/* states */            seqg_states_ssOnOff,
	/* number of states */  24
	},
};

/* Program table (global) */
seqProgram sncExample = {
	/* magic number */      2002004,
	/* program name */      "sncExample",
	/* channels */          seqg_chans,
	/* num. channels */     138,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME sncExample
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sncExampleRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sncExample);
}
epicsExportRegistrar(sncExampleRegistrar);
